### ISSUE TITLE
Obtain dependencies via Gradle / Central Repository

### ISSUE THREAD

**Issue by k0105** [k0105/ensemble#2]
All dependencies except for simmetrics should be obtainable via Central Repository. I got a bit paranoid, since quite a few external QA projects broke for me in the past when their libraries became unavailable and I currently (since I'm travelling) don't have the resources to maintain my own Maven repository (the clean solution), but nevertheless I should and will add the option to download all dependencies if possible.

Note: Waiting for update to continue, since this might change thrift dependency.

**Comment by k0105** [comment]
Done.

**Comment by mpkorstanje** [comment]
Hi. I appear to be the maintainer of [Simmetrics](https://github.com/Simmetrics/simmetrics) on github. It is available on maven central. 

You should be aware that it has been somewhat refactored. You have to be explicit in choosing what to measure (e.g. similarity between words, q-grams, ect).  Some subtle and not so subtle bugs have been fixed and large amounts of cruft have been removed.

**Comment by k0105** [comment]
@mpkorstanje Thank you very much. It already works fine and Simmetrics is a very useful library. Working with it was a breeze - thanks for maintaining it.

**Comment by mpkorstanje** [comment]
You're welcome. No worries.
